# Project: Calculator
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Scan.o Print.o calculation.o
LINKOBJ  = main.o Scan.o Print.o calculation.o
LIBS     = -L"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/lib" -L"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/include" -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/include" -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/»ÆÐñ/Desktop/031502311/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Calculator.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Scan.o: Scan.cpp
	$(CPP) -c Scan.cpp -o Scan.o $(CXXFLAGS)

Print.o: Print.cpp
	$(CPP) -c Print.cpp -o Print.o $(CXXFLAGS)

calculation.o: calculation.cpp
	$(CPP) -c calculation.cpp -o calculation.o $(CXXFLAGS)
